#!/usr/bin/env rake
require "bundler/setup"
require "bundler/gem_tasks"

# Tests
require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.pattern = "test/**/test_*.rb"
end

task :default => :test
